### ISSUE TITLE
Getting a compile error on this line

### ISSUE THREAD

**Issue by jeroenleenarts** [pia-foss/tunnel-apple#16]
# Summary
Compile error in Xcode 9.2

### Steps to reproduce
Clone repo, build

### What is the current bug behavior?
Failed build

(What actually happens)

### What is the expected correct behavior?
Succesful build

(What you should see instead)

### Possible fixes suggested remediation
Add a parameter to the call on this location: https://github.com/pia-foss/tunnel-apple/blob/f0ead33545da0b2e2be91cc5f45a90590db921ad/PIATunnel/Sources/Core/SecureRandom.swift#L65

~suggestion

~major

**Comment by jeroenleenarts** [comment]
Building with Xcode 9.4 resolved the issue.

**Comment by keeshux** [comment]
Thanks for reporting @jeroenleenarts. Pretty sure it's one of the often breaking changes introduced by Swift updates. Will update the README accordingly or try to constrain the Swift version to a compatible one.
